- name: Create CFSSL CA Secret Job Service Account
  k8s:
    state: present
    definition: "{{ lookup('template', 'cfssl-ca-secret-job-rbac.yml') }}"
  when: k8s_use_rbac

- name: Ensure CFSSL CA Secret Job
  k8s:
    state: present
    definition: "{{ lookup('template', 'cfssl-ca-secret-job.yml') }}"
