- name: Ensure Astarte namespace
  k8s:
    name: "{{ astarte_k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create CFSSL CA Secret Job Service Account
  k8s:
    state: present
    definition: "{{ lookup('template', 'cfssl-ca-secret-job-rbac.yml') }}"
  when: k8s_use_rbac

- name: Ensure CFSSL CA Secret Job
  k8s:
    state: present
    definition: "{{ lookup('template', 'cfssl-ca-secret-job.yml') }}"
