version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  # Disable all linters by default and enable only the ones we want
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - staticcheck
    - lll
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings

formatters:
  enable:
    - gofmt
    - goimports
