# Adds namespace to all resources.
namespace: "{{ .Release.Namespace }}"
namePrefix: "{{ .Release.Name }}-"

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# the following config is for teaching kustomize how to do var substitution
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../webhook
- ../certmanager
patches:
- path: webhookcainjection_patch.yaml
- path: helm-certificate_patch.yaml
replacements:
- source: # CERTIFICATE NAMESPACE
    kind: Certificate
    name: serving-cert
    fieldPath: metadata.namespace
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 0
    select:
      annotationSelector: cert-manager.io/inject-ca-from
- source: # CERTIFICATE NAME
    kind: Certificate
    name: serving-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      annotationSelector: cert-manager.io/inject-ca-from
- source: # SERVICE NAMESPACE
    kind: Service
    name: webhook-service
    fieldPath: metadata.namespace
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
  - fieldPaths:
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
- source: # SERVICE NAME
    kind: Service
    name: webhook-service
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
  - fieldPaths:
    - spec.dnsNames.1
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
  - fieldPaths:
    - spec.secretName
    options:
      delimiter: '-'
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
