- name: Ensure Astarte namespace
  k8s:
    name: "{{ astarte_k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Ensure Voyager API Ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'voyager-ingress.yml') }}"
