apiVersion: v1
kind: Secret
metadata:
  name: {{ resources_computed_prefix }}voyager-acme-account
  namespace: {{ astarte_k8s_namespace }}
type: Opaque
data:
  ACME_EMAIL: {{ voyager_letsencrypt_acme_email | b64encode }}
