# permissions for end users to edit astartes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: astarte-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: astarte-kubernetes-operator
    app.kubernetes.io/part-of: astarte-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: astarte-editor-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/status
  verbs:
  - get
