# permissions for end users to edit flows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: astarte-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: flow-flow-editor-role
rules:
- apiGroups:
  - flow.astarte-platform.org
  resources:
  - flows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flow.astarte-platform.org
  resources:
  - flows/status
  verbs:
  - get
