# This rule is not used by the project astarte-kubernetes-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ingress.astarte-platform.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: astarte-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: ingress-astartefdoingress-viewer-role
rules:
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartefdoingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartefdoingresses/status
  verbs:
  - get
