# permissions for end users to view astartedefaultingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: astarte-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: ingress-astartedefaultingress-viewer-role
rules:
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses/status
  verbs:
  - get
