---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/finalizers
  verbs:
  - update
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.astarte-platform.org
  resources:
  - flows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - flows/finalizers
  verbs:
  - update
- apiGroups:
  - api.astarte-platform.org
  resources:
  - flows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses/status
  verbs:
  - get
  - patch
  - update
