---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: astarte-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/finalizers
  verbs:
  - update
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/status
  verbs:
  - get
  - patch
  - update
