apiVersion: v1
kind: Service
metadata:
  labels:
    app: vernemq
  name: vernemq
  namespace: {{ astarte_k8s_namespace }}
  annotations:
    # Rely on PROXYv2 when accepting connections from Voyager (HAProxy)
    ingress.appscode.com/send-proxy: v2-ssl-cn
    # Check upon the backend
    ingress.appscode.com/check: "true"
spec:
  clusterIP: None
  ports:
    - name: mqtt
      port: 1883
    - name: mqtt-reverse
      port: 1885
  selector:
    app: vernemq

