apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ resources_computed_prefix }}vernemq
  name: {{ resources_computed_prefix }}vernemq
  namespace: {{ astarte_k8s_namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ resources_computed_prefix }}vernemq
  name: {{ resources_computed_prefix }}vernemq
  namespace: {{ astarte_k8s_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ resources_computed_prefix }}vernemq
  name: {{ resources_computed_prefix }}vernemq
  namespace: {{ astarte_k8s_namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ resources_computed_prefix }}vernemq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ resources_computed_prefix }}vernemq

