apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: astarte-kubernetes-operator.v24.11.0-dev
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AstarteDefaultIngress is the Schema for the astartedefaultingresses
        API
      displayName: Astarte Default Ingress
      kind: AstarteDefaultIngress
      name: astartedefaultingresses.ingress.astarte-platform.org
      version: v1alpha1
    - description: Astarte is the Schema for the astartes API
      displayName: Astarte
      kind: Astarte
      name: astartes.api.astarte-platform.org
      version: v2alpha1
    - description: Flow is the Schema for the flows API
      displayName: Flow
      kind: Flow
      name: flows.flow.astarte-platform.org
      version: v2alpha1
  description: The Astarte Kubernetes Operator bundle.
  displayName: astarte-kubernetes-operator
  icon:
  - base64data: ""
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - astarte
  - operator
  - iot
  - dataorchestration
  links:
  - name: Astarte Kubernetes Operator
    url: https://github.com/astarte-platform/astarte-kubernetes-operator
  maintainers:
  - email: dario.freddi@ispirata.com
    name: drf
  - email: mattia.mazzucato@secomind.com
    name: matt-mazzucato
  - email: arnaldo.cesco@secomind.com
    name: annopaolo
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: Astarte Platform
    url: https://github.com/astarte-platform
  version: 24.11.0-dev
