apiVersion: v2
name: astarte-operator
description: The Astarte Kubernetes Operator Helm Chart.
type: application

version: "26.7.0-rc.2"
appVersion: "26.7.0-rc.2"
kubeVersion: ">= 1.19.0-0"

home: https://github.com/astarte-platform/astarte-kubernetes-operator
sources:
  - https://github.com/astarte-platform/astarte-kubernetes-operator
keywords:
  - astarte
  - operator
  - iot
  - dataorchestration
maintainers:
  - name: matt-mazzucato
    email: mattia.mazzucato@secomind.com
  - name: annopaolo
    email: arnaldo.cesco@secomind.com
  - email: luca.marchiori@secomind.com
    name: lucamarchiori
  - email: guilherme.crocetti@secomind.com
    name: guicrocetti
icon: https://raw.githubusercontent.com/astarte-platform/astarte-kubernetes-operator/release-26.7/docs/documentation/images/clea_bw.png
