# Adds namespace to all resources.
namespace: '{{ .Release.Namespace }}'
namePrefix: '{{ .Release.Name }}-'

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../rbac
