k8s_service_name: "{{ astarte_app_name | regex_replace('_', '-') }}"
k8s_deployment_name: "{{ resources_computed_prefix }}{{ k8s_service_name }}"
k8s_deployment_replicas: 1
k8s_deployment_image: "{{ astarte_distribution_channel }}/astarte_{{ astarte_app_name }}:{{ astarte_tag }}"
k8s_deployment_image_pull_policy: "{{ astarte_image_pull_policy }}"
k8s_deployment_resources_requests_cpu: 100m
k8s_deployment_resources_requests_memory: 128M
k8s_deployment_resources_limits_cpu: 200m
k8s_deployment_resources_limits_memory: 256M
k8s_erlang_cookie_name: "{{ resources_computed_prefix }}{{ k8s_service_name }}-cookie"
astarte_app_amqp_connection_host: "{{ vars | json_query('rabbitmq.connection.host') | default(rabbitmq_connection_host, true) }}"
astarte_app_cassandra_nodes: "{{ vars | json_query('cassandra.nodes') | default(cassandra_nodes, true) }}"

k8s_deployment_additional_volume_mounts:
k8s_deployment_additional_variables:
k8s_deployment_additional_secret_volumes:
k8s_deployment_additional_secret_variables:
