apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: {{ astarte_k8s_namespace }}
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra

