# Adds namespace to all resources.
namespace: '{{ .Release.Namespace }}'
namePrefix: '{{ .Release.Name }}-'

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue



# This is needed due to the fact we don't have access to the full kustomization, hence we cannot replace
# variables. On the other hand, all our resources are CRDs, so we can rely on commonAnnotations, which will
# still take precedence over the other patches.
commonAnnotations:
  cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert'
  helm.sh/resource-policy: keep
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
patches:
- path: service-name-helm_patch.yaml
