apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: astartes.api.astarte-platform.org
spec:
  conversion:
    webhook:
      clientConfig:
        service:
          name: '{{ .Release.Name }}-webhook-service'
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flows.api.astarte-platform.org
spec:
  conversion:
    webhook:
      clientConfig:
        service:
          name: '{{ .Release.Name }}-webhook-service'
