apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ resources_computed_prefix }}cfssl
  name: {{ resources_computed_prefix }}cfssl
  namespace: {{ astarte_k8s_namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ resources_computed_prefix }}cfssl
