apiVersion: v1
kind: ConfigMap
metadata:
  name: cfssl-config
  namespace: {{ astarte_k8s_namespace }}
data:
  db_config.json: >
    {{ lookup('vars', 'cfssl.db_config', default=cfssl_db_config) | to_json }}
  csr_root_ca.json: >
    {{ lookup('vars', 'cfssl.csr_root_ca', default=cfssl_csr_root_ca) | to_json }}
  ca_root_config.json: >
    {{ lookup('vars', 'cfssl.ca_root_config', default=cfssl_ca_root_config) | to_json }}
