apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ resources_computed_prefix }}{{ k8s_service_name }}-api
    astarte-service: {{ k8s_service_name }}
    component: astarte
  name: {{ resources_computed_prefix }}{{ k8s_service_name }}
  namespace: {{ astarte_k8s_namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ astarte_app_api_port }}
  selector:
    app: {{ resources_computed_prefix }}{{ k8s_service_name }}-api

