cassandra_k8s_enable_antiaffinity: "{{ lookup('vars', 'cassandra.anti_affinity', default=true) }}"

cassandra_image_tag: "{{ lookup('vars', 'cassandra.version', default='3.11.3') }}"
cassandra_cluster_size: "{{ lookup('vars', 'cassandra.replicas', default='1') }}"
cassandra_max_heap_size: "{{ lookup('vars', 'cassandra.max_heap_size', default='1024M') }}"
cassandra_heap_new_size: "{{ lookup('vars', 'cassandra.heap_new_size', default='256M') }}"
cassandra_resources_requests_cpu: "{{ lookup('vars', 'cassandra.resources.requests.cpu', default='1000m') }}"
cassandra_resources_requests_memory: "{{ lookup('vars', 'cassandra.resources.requests.memory', default='1024M') }}"
cassandra_resources_limits_cpu: "{{ lookup('vars', 'cassandra.resources.limits.cpu', default='2000m') }}"
cassandra_resources_limits_memory: "{{ lookup('vars', 'cassandra.resources.limits.memory', default='2048M') }}"
cassandra_k8s_storage_class_name: "{{ lookup('vars', 'cassandra.storage.class_name', default=k8s_storage_class_name) }}"
cassandra_k8s_volume_size: "{{ lookup('vars', 'cassandra.storage.size', default='30Gi') }}"

cassandra_k8s_volume_definition: "{{ lookup('vars', 'cassandra.storage.volume_definition', default='') }}"
