apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ resources_computed_prefix }}generic-erlang-configuration
  namespace: {{ astarte_k8s_namespace }}
data:
  vm.args: |
      ## Name of the node
      -name ${RELEASE_NAME}@${MY_POD_IP}

      ## Cookie for distributed erlang
      -setcookie ${ERLANG_COOKIE}

      ## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
      ## (Disabled by default..use with caution!)
      ##-heart

      ## Enable kernel poll and a few async threads
      ##+K true
      ##+A 5

      ## Increase number of concurrent ports/sockets
      ##-env ERL_MAX_PORTS 4096

      ## Tweak GC to run more often
      ##-env ERL_FULLSWEEP_AFTER 10

      # Enable SMP automatically based on availability
      -smp auto
