apiVersion: v1
kind: Secret
metadata:
  name: {{ astarte_housekeeping_key_secret }}
  namespace: {{ astarte_k8s_namespace }}
type: Opaque
data:
  public-key: {{ lookup('file', '/tmp/astarte_housekeeping_private_key.pub') | b64encode }}
