apiVersion: v1
kind: Secret
metadata:
  name: {{ rabbitmq_connection_k8s_credentials_secret_name }}
  namespace: {{ astarte_k8s_namespace }}
type: Opaque
data:
  {{ rabbitmq_connection_k8s_credentials_secret_username_key }}: {{ rabbitmq_connection_username | b64encode }}
  {{ rabbitmq_connection_k8s_credentials_secret_password_key }}: {{ rabbitmq_connection_password | b64encode }}
