apiVersion: v1
kind: Secret
metadata:
  name: {{ resources_computed_prefix }}rabbitmq-cookie
  namespace: {{ astarte_k8s_namespace }}
type: Opaque
data:
  erlang-cookie: {{ lookup('password', '/dev/null length=32 chars=ascii_letters') | b64encode }}
