apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ resources_computed_prefix }}rabbitmq
  name: {{ resources_computed_prefix }}rabbitmq
  namespace: {{ astarte_k8s_namespace }}
spec:
  # Allow DNS only
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
  selector:
    app: {{ resources_computed_prefix }}rabbitmq

