apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: {{ astarte_k8s_namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: {{ astarte_k8s_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: {{ astarte_k8s_namespace }}
subjects:
  - kind: ServiceAccount
    name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq

