#
# This file is part of Astarte.
#
# Copyright 2023 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Docs generation

on:
  push:
    paths:
    # Documentation
    - 'docs/**'
    # APIs
    - 'apis/**'
    # The workflow itself
    - '.github/workflows/generate-docs.yaml'
    branches:
    # Create the snapshot only when it matters
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
    # Checkout the source
    - uses: actions/checkout@v4
      with:
        path: astarte-kubernetes-operator
    # Checkout the docs repository
    - uses: actions/checkout@v4
      with:
        repository: astarte-platform/docs
        ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
        path: docs
    # Setup Go for crd-ref-docs (ubuntu-20.04 defaults to go 1.15)
    # see https://github.com/actions/virtual-environments/issues/2447
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    # Generate CRD docs directory for Hugo
    - run: mkdir docs/content
      working-directory: astarte-kubernetes-operator
    # Generate CRD docs
    - run: |
        make crd-docs
        echo $(ls docs/content)
        echo $(wc -l docs/content/index.md)
      working-directory: astarte-kubernetes-operator
    - name: Check generated crd-docs
      run: |
        echo $(ls docs/content)
        echo $(wc -l docs/content/index.md)
      working-directory: astarte-kubernetes-operator
    # Install Hugo
    - run: |
        curl -Lo hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.139.2/hugo_extended_0.139.2_Linux-64bit.tar.gz
        tar -zxvf hugo.tar.gz hugo
      working-directory: astarte-kubernetes-operator
    # Checkout the hugo-book theme
    - name: Checkout hugo-book
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: alex-shpak/hugo-book
        ref: 7c78a39c531aa2492ed7e92f2ce9dfb2c8c0d3fa
        path: astarte-kubernetes-operator/themes/hugo-book
    - name: Set docs dirname
      run: |
        DOCS_DIRNAME="astarte-kubernetes-operator/$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-//g')"
        echo "DOCS_DIRNAME=$DOCS_DIRNAME" >> $GITHUB_ENV
    - name: Apply docs dirname to Hugo config
      run: |
          echo "baseURL: https://docs.astarte-platform.org/$DOCS_DIRNAME/crds" >> docs/hugo/config.yaml
      working-directory: astarte-kubernetes-operator
    # Run hugo to build docs page
    - name: Build CRD docs
      run: ./hugo --config docs/hugo/config.yaml --contentDir docs/content --destination docs/generated --logLevel debug
      working-directory: astarte-kubernetes-operator
    - name: Check built CRD reference page
      run: |
        echo $(ls docs/generated)
        echo $(wc -l docs/generated/index.html)
      working-directory: astarte-kubernetes-operator
    - uses: erlef/setup-beam@v1.17
      with:
        otp-version: "25.3.2"
        elixir-version: "1.14.5"
    - name: Install Dependencies
      working-directory: astarte-kubernetes-operator/docs/documentation
      run: mix deps.get
    - name: Build Docs
      working-directory: astarte-kubernetes-operator/docs/documentation
      run: mix docs
    - name: Copy Docs
      run: |
        rm -rf docs/$DOCS_DIRNAME
        mkdir -p docs/$DOCS_DIRNAME/crds
        cp -r astarte-kubernetes-operator/docs/generated/* docs/$DOCS_DIRNAME/crds
        cp -r astarte-kubernetes-operator/docs/documentation/doc/* docs/$DOCS_DIRNAME
    - name: Commit files
      working-directory: ./docs
      run: |
        git config --local user.email "astarte-machine@ispirata.com"
        git config --local user.name "Astarte Bot"
        git add .
        git commit -m "Update Astarte Kubernetes Operator documentation"
    - name: Push changes
      working-directory: ./docs
      run: |
        git push origin master
